#ifndef GAS_CAMARA_LIBARY_GLOBAL_H
#define GAS_CAMARA_LIBARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GAS_CAMARA_LIBARY_LIBRARY)
#  define GAS_CAMARA_LIBARY_EXPORT Q_DECL_EXPORT
#else
#  define GAS_CAMARA_LIBARY_EXPORT Q_DECL_IMPORT
#endif

#endif // GAS_CAMARA_LIBARY_GLOBAL_H
